config/routes.rb
Rails.application.routes.draw do
  resources :weapons
 resources :users, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	enum kind: [ :knight, :wizard ]

	validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

	def title
		"#{self.kind} #{self.nickname} ##{self.level}"
	end	
end

app/models/weapon.rb
class Weapon < ApplicationRecord
	validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

	def current_power
		self.power_base + ((self.level - 1) * self.power_step)
	end

	def title
		"#{self.name}##{self.level}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def create
  	@user = User.create(user_params)
  	redirect_to users_path
  end

  private

  def user_params
  	params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:destroy, :show]

  def index
  	@weapons = Weapon.all
  end

  def create
  	@weapon = Weapon.create(weapon_params)
  	redirect_to weapons_path
  end

  def destroy
  	@weapon.destroy
  	redirect_to weapons_path
  end

  def show
  end

  private

  def set_weapon
  	@weapon = Weapon.find(params[:id])
  end

  def weapon_params
  	params.require(:weapon).permit(:name, :level, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecStudy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<p><%= user.title %></p>
<% end %>

app/views/weapons/index.html.erb
<% @weapons.each do |weapon| %>
	<p><%= weapon.name %></p>

	<p><%= weapon.current_power %></p>

	<p><%= weapon.title %></p>

	<p><%= link_to 'Show', weapon_path(weapon) %></p>

	<hr />
<% end %>

app/views/weapons/show.html.erb
<p><%= @weapon.name %></p>

<p><%= @weapon.description %></p>

<p><%= @weapon.current_power %></p>

<p><%= @weapon.power_base %></p>

<p><%= @weapon.power_step %></p>

<p><%= @weapon.title %></p>

<p><%= link_to weapon_path(@weapon) %></p>

<%= link_to 'Voltar', weapons_path %>